//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Agriculture.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AgricultureEntities7 : DbContext
    {
        public AgricultureEntities7()
            : base("name=AgricultureEntities7")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BuyFertilizer> BuyFertilizers { get; set; }

        public System.Data.Entity.DbSet<Agriculture.Models.BuyMachine> BuyMachines { get; set; }

        public System.Data.Entity.DbSet<Agriculture.Models.BuyPestiside> BuyPestisides { get; set; }
    }
}
